# Generated by Django 4.1.6 on 2023-04-26 06:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=30, unique=True)),
                ('DateOfBirth', models.CharField(max_length=70)),
                ('firebase_password', models.CharField(blank=True, max_length=250, null=True)),
                ('firebase_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='ProfilePic')),
            ],
        ),
    ]
